package packets

const PACKET_HANDSHAKE = 0x00
const (
	PACKET_PING                = 0x01
	PACKET_PONG                = 0x01
	PACKET_LOGIN_SUCCESS       = 0x02
	PACKET_LOGIN_DISCONNECT    = 0x00
	PACKET_ENCRYPTION_REQUEST  = 0x01
	PACKET_ENCRYPTION_RESPONSE = 0x01
)
