package packets

const PACKET_HANDSHAKE = 0x00
const (
	PACKET_PING byte = 0x01
	PACKET_PONG byte = 0x01

	PACKET_LOGIN_AKNOWLEDGED int32 = 0x03
	PACKET_LOGIN_SUCCESS     byte  = 0x02
	PACKET_LOGIN_DISCONNECT  byte  = 0x00

	PACKET_ENCRYPTION_REQUEST  byte = 0x01
	PACKET_ENCRYPTION_RESPONSE byte = 0x01

	PACKET_SET_COMPRESSION byte = 0x03

	PACKET_REGISTRY_DATA int32 = 0x07
)
