//go:generate go build -o exec .
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

type TranslationCodesFileWriter struct {
	file *os.File
}

func (t *TranslationCodesFileWriter) Close() error {
	if _, err := t.file.WriteString(")"); err != nil {
		return err
	}
	return t.file.Close()
}

func New(file *os.File, release string) (*TranslationCodesFileWriter, error) {

	fmt.Fprintf(file, `// Auto generated by minecraft-core autogen; DO NOT EDIT Manually
// Generated for Minecraft %s
package shared

const (
		`, release)

	return &TranslationCodesFileWriter{
		file: file,
	}, nil
}

func (t *TranslationCodesFileWriter) Write(key, value string) error {
	_, err := fmt.Fprintf(t.file, "\t%s = \"%s\" // %q\n", sanitize([]rune(key)), key, value)
	return err
}

func main() {
	startingDir := os.Args[1]
	langFolder := os.Args[2]
	releaseName := os.Args[3]

	os.MkdirAll(startingDir, 0777)

	os.Chdir(startingDir)
	f, err := os.OpenFile(
		"translation_codes.go",
		os.O_CREATE|os.O_WRONLY|os.O_TRUNC,
		0777,
	)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	writer, err := New(f, releaseName)
	if err != nil {
		panic(err)
	}

	langCodesF, err := os.Open(filepath.Join(langFolder, "en_us.json"))
	if err != nil {
		panic(err)
	}

	var data map[string]string
	if err := json.NewDecoder(langCodesF).Decode(&data); err != nil {
		langCodesF.Close()
		panic(err)
	}
	langCodesF.Close()

	for key, value := range data {
		if err := writer.Write(key, value); err != nil {
			panic(err)
		}
	}

	writer.Close()
}
