// Auto generated by minecraft-core autogen; DO NOT EDIT.
// Generated for Minecraft 1.20.4
package worldgen

type Layer struct {
	Block  string
	Height int
}

type FlatGeneratorSettings struct {
	Biome             string
	Features          bool
	Lakes             bool
	Layers            []Layer
	StructureOverrides []string
}

type Generator struct {
	Type         string
	FlatSettings *FlatGeneratorSettings
	BiomeSource  []byte
	Settings     []byte
}

type Dimension struct {
	Type      string
	Generator Generator
}

type WorldPreset struct {
	Dimensions map[string]Dimension
}

var WorldPreset_overworld = WorldPreset{
	Dimensions: map[string]Dimension{
		"minecraft:overworld": {
			Type: "minecraft:overworld",
			Generator: Generator{
				Type:        "minecraft:noise",
				BiomeSource: []byte(`{"type":"minecraft:multi_noise","preset":"minecraft:overworld"}`),
				Settings:    []byte(`"minecraft:overworld"`),
			},
		},
		"minecraft:the_end": {
			Type: "minecraft:the_end",
			Generator: Generator{
				Type:        "minecraft:noise",
				BiomeSource: []byte(`{"type":"minecraft:the_end"}`),
				Settings:    []byte(`"minecraft:end"`),
			},
		},
		"minecraft:the_nether": {
			Type: "minecraft:the_nether",
			Generator: Generator{
				Type:        "minecraft:noise",
				BiomeSource: []byte(`{"type":"minecraft:multi_noise","preset":"minecraft:nether"}`),
				Settings:    []byte(`"minecraft:nether"`),
			},
		},
	},
}

var KnownWorldPresets = []string{
	"overworld",
}