package damagetype

import (
	"fmt"
	"io"
)

type RawDamageType struct {
	Exhaustion       float32 `json:"exhaustion"`
	MessageID        string  `json:"message_id"`
	Scaling          string  `json:"scaling"`
	DeathMessageType string  `json:"death_message_type,omitempty"`
}

type DamageType struct {
	Exhaustion       float32
	MessageID        string
	Scaling          string
	DeathMessageType string
}

type DamageTypeFileWriter struct {
	w          io.Writer
	knownTypes []string
}

func NewDamageTypeFileWriter(w io.Writer, release string) *DamageTypeFileWriter {
	fmt.Fprintf(w, `// Auto generated by minecraft-core autogen; DO NOT EDIT.
// Generated for Minecraft %s
package damage_type

type DamageType struct {
	Exhaustion       float32
	MessageID        string
	Scaling          string
	DeathMessageType string
}

`, release)

	return &DamageTypeFileWriter{w: w}
}

func (w *DamageTypeFileWriter) WriteObject(name string, d DamageType) {

	fmt.Fprintf(w.w, "var Damage_%s = DamageType{\n", name)
	fmt.Fprintf(w.w, "\tExhaustion: %f,\n", d.Exhaustion)
	fmt.Fprintf(w.w, "\tMessageID: \"%s\",\n", d.MessageID)
	fmt.Fprintf(w.w, "\tScaling: \"%s\",\n", d.Scaling)

	if d.DeathMessageType != "" {
		fmt.Fprintf(w.w, "\tDeathMessageType: \"%s\",\n", d.DeathMessageType)
	}

	fmt.Fprintln(w.w, "}\n")

	w.knownTypes = append(w.knownTypes, name)
}

func (w *DamageTypeFileWriter) Finish() {
	fmt.Fprint(w.w, "var KnownDamageTypes = []string{\n")
	for _, k := range w.knownTypes {
		fmt.Fprintf(w.w, "\t\"%s\",\n", k)
	}
	fmt.Fprintln(w.w, "}")
}
